spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/school_tracking}
    username: ${DB_USER:school}
    password: ${DB_PASSWORD:school}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
  sql:
    init:
      mode: always
  jackson:
    default-property-inclusion: non_null

server:
  port: ${SERVER_PORT:8080}